server {
    listen 8080;

    location /api/ {
        proxy_pass https://ratio-api-211392956944.us-central1.run.app/;
        proxy_set_header Host ratio-api-211392956944.us-central1.run.app;
        proxy_ssl_server_name on;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location / {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
        try_files $uri /index.html;
    }
}
